### ISSUE TITLE
Index aktualisieren

### ISSUE THREAD

**Issue by lutz** [unilinks/data#2]
Das alte System dass die `index.json` so nicht mehr funktioniert, weil wir ja jetzt mehrere Dateien pro Studiengang haben. Wir könnten in der `index.json` auch ein Model einführen dass pro Studiengang ein Liste von den relativen Pfaden zu den dafür benötigten Dateien wiedergibt. Dann müsste die Webseite dies nur entsprechend verarbeiten

**Comment by jklmnn** [comment]
Also, erst mal habe ich das alte System mit https://github.com/unilinksproject/unilinks/commit/a35de18051d2e3e13a8d00f59bef150342e8be17 nach unilinksproject migriert. https://jkliemann.de/unilinks zeigt jetzt auf https://unilinksproject.github.io/unilinks. Außerdem habe ich das CDN von RawGit zu jsDelivr geändert, siehe [Grund](https://rawgit.com/).
Ich hab das jetzt erst mal hier reingeschrieben, ein eigenes Issue dafür lohnt sich mMn. nicht.

Ich finde es gut, dass du die Daten neu strukturierst. Aber mir fehlt leider die Zeit die Webseite entsprechend umzubauen. Aktuell ist der Code der die Daten lädt vanilla JS. Ich hatte mir vor einer Weile mal Angular angeschaut und das schien konzeptuell ganz gut zu passen (man kann quasi ein Mapping von Links als Quelle auf HTML-Objekte als Datenausgabe erstellen, was wir ja im Prinzip wollen). Allerdings ist das schon eine Weile her und ich habe aktuell weder Zeit noch Ambitionen mich mit Webentwicklung zu befassen (hatte ich früher schon nicht besonders, deswegen ist ja alles in Bootstrap ;)).

Deswegen würde ich dir da in der Entwicklung einer neuen Webseite freie Hand lassen. Du kannst auch gerne noch mehr Leute in das Projekt ziehen ;) Ich würde ein Modell vorschlagen, dass in den Master bzw. GH-Branch der jeweiligen Repos hauptsächlich über Pull-Requests gemerged wird und ich dann mit reviewe. Ich werde aber selbst keine Entwicklungsarbeit mehr leisten.

**Comment by lutz** [comment]
Die Umleitung von [https://jkliemann.de/unilinks](https://jkliemann.de/unilinks) auf [https://unilinksproject.github.io/unilinks](https://unilinksproject.github.io/unilinks) scheint nicht zu funktionieren, da kommt ein 404 Fehler. Das mit dem Pull Request Modell können wir gerne so machen. Ich werde bei mir mal rumfragen wer Bock hat die Webseite zu machen ( ich habe auch nicht viele Ambitionen zur Webentwicklung).

**Comment by jklmnn** [comment]
Sorry, ich meinte https://jkliemann.de/unilinks.html. Das mit dem 404 ist kein Problem, ich hatte nur das html vergessen, der andere Link sollte nicht bekannt sein.

**Comment by lutz** [comment]
@jklmnn  so ich habe jetzt @flueders als Teammitglied gewonnen. Er wird sich die Webseite anschauen.

**Comment by lutz** [comment]
Also neue `index.json` stelle ich mir wie gesagt eine Art liste für jeden Studiengang vor, die dann alle Dateien enthält, die angezeigt werden müssen. Die Frage ist kann mann mit JavaScript das so dynamisch parsen und zusammenbauen auf Client Seite! @flueders Du hast ja schon mehre mit Webanwendungen zu tun gehabt.

**Comment by lutz** [comment]
```
{
  "courses": [
    {
      "name": "Elektrotechnik (AMR)",
      "files": [
        "allg.json",
        "et.gs.json",
        "et.hs.amr.json"
      ]
    },
    {
      "name": "Elektrotechnik (EET)",
      "files": [
        "allg.json",
        "et.gs.json",
        "et.hs.eet.json"
      ]
    },
	,
    {
      "name": "Elektrotechnik (GMM)",
      "files": [
        "allg.json",
        "et.gs.json",
        "et.hs.gmm.json"
      ]
    },
	,
    {
      "name": "Elektrotechnik (IT)",
      "files": [
        "allg.json",
        "et.gs.json",
        "et.hs.it.json"
      ]
    },
	,
    {
      "name": "Elektrotechnik (MEL)",
      "files": [
        "allg.json",
        "et.gs.json",
        "et.hs.mel.json"
      ]
    },
	,
    {
      "name": "Informationssystemtechnik",
      "files": [
        "allg.json",
        "ist.gs.json",
        "ist.hs.json"
      ]
    },
	,
    {
      "name": "Mechatronik",
      "files": [
        "allg.json",
        "mt.gs.json",
        "mt.hs.json"
      ]
    },
	,
    {
      "name": "Regenerative Energiesysteme",
      "files": [
        "allg.json",
        "res.gs.json",
        "res.hs.json"
      ]
    },
  ]
}
```

**Comment by lutz** [comment]
Der Vorteil von so einem System wäre es, die Liste der Listen grundsätzlich leicht zu erweitern. Falls man mal separate `allg.json` einführen will usw.

**Comment by lutz** [comment]
Ich habe die Änderungen im `dev` Branch eingepflegt!
