### ISSUE TITLE
Sprache der Dokumentation

### ISSUE THREAD

**Issue by lutz** [unilinks/data#3]
Wir sollten uns überlegen ob wir in **Englisch** oder in **Deutsch** die Dokumentation verfassen wollen. Ich würde **Deutsch** vorschlagen, weil es deutsche Studiengänge sind und wir die Issues usw. ja auch in **Deutsch** verfassen. Unter Dokumentation verstehe ich sowas wir die `readme.md` Seiten, die Erklärung des TAG Systemes usw.

**Comment by jklmnn** [comment]
Eigentlich ist es auf Deutsch weil es irgendwann mal so angefangen hat. Ansonsten bin ich für Englisch. Erstens haben wir nicht nur deutsche Studenten, zweitens sollten die deutschen Studenten Englisch können und drittens finde ich es ehrlich gesagt immernoch seltsam irgendwas auf GitHub in Deutsch zu machen.

**Comment by lutz** [comment]
Naja der Anteil deutschsprechender Studenten ist sicherlich größer und bei GitHub wäre das einerlei, weil es ja keine Regel gibt die vorschreibt welche Sprache man nehmen muss. Vorschlag zu Güte, wir machen einfach beides. GitHub bietet leider keine Lokalisierung an, aber es gibt interessante Konzepte um so etwas anzubieten. Dann lernen wir auch gleich noch was dazu

**Comment by jklmnn** [comment]
Mit Englisch erreichst du halt alle Studenden und nicht nur den größeren Anteil ;)
Mir persöhnlich ist es ehrlich gesagt egal, ich werde ja selbst wahrscheinlich keine neuen Inhalte generieren.

**Comment by lutzbox** [comment]
(Hier)[https://webapps.stackexchange.com/questions/30567/internationalization-of-the-github-wiki-or-github-pages] mal eine Diskussion zur Lokalisierung

**Comment by lutz** [comment]
[Hier](https://webapps.stackexchange.com/questions/30567/internationalization-of-the-github-wiki-or-github-pages) mal eine Diskussion zu der möglichen Umsetzung

**Comment by flueders** [comment]
Meine Meinung wäre ganz klar: Deutsch. Die Lehrveranstaltungen an der Uni sind ja (zumindest in den unteren Semstern) auch alle auf deutsch. Auch der FSR stellt seine Infos fast nur auf deutsch zur Verfügung.

Die Frage, die ich mir eigentlich stelle, ist, was hier überhaupt groß dokumentiert werden soll...? Bislang ist doch alles mehr oder weniger selbstsprechend

**Comment by lutz** [comment]
@flueders Aus meiner Sicht sind das folgende Dinge:

- Tag Aufbau, weil ja darüber die aktuellen Daten gezogen werden können, wenn man nicht direkt auf die RAW Daten geht
- Json Modell
- Ziele und mögliche Mitarbeit am Projekt (readme.md) sowie ein paar kurze Sätze bzw. Verlinkungen zur verwendeten Lizenz. Aus Erfahrung weiß ich dass dass die Leute in der Regel auch nicht so Recht damit umzugehen wissen, weil es einfach Recht viele gibt
