### ISSUE TITLE
Notenscript

### ISSUE THREAD

**Issue by flueders** [unilinks/data#4]
Ich habe mal das Notenscript ausprobiert, dazu die Anmerkungen:

- es fehlt jeweils in der Readme der Parameter -i:
`python noten.py --gen **-i** et.gs`
- das Script funktioniert nur richtig für die Dateien, in denen noch nicht die Abschnitte (also Semester) verwendet werden. Konkret geht z. B. `et.gs`, `ist` aber nicht

Daher die Frage: Script korrigieren, oder erstmal aus dem Projekt rausnehmen und ggf. später nochmal neu entwickeln? Das könnte man dann auch in Javascript schreiben und dann einfach auf der Seite integrieren, was sicher etwas einfacher zu handhaben ist

**Comment by lutz** [comment]
Die Idee war eigentlich das ganze Noten berechnen, erst mal rauszunehmen und später als separates Projekt zu führen.

**Comment by lutz** [comment]
Ich habe die Datei `noten.py` aus dem `dev` Branch entfernt!
