### ISSUE TITLE
Versionierung anpassen

### ISSUE THREAD

**Issue by lutz** [unilinks/data#8]
Mein Vorschlag wäre das wir die Versionierung vereinfachen in dem wir am dem WS 19/20 auf das Format  `yyyy-mm-dd` also z.B. **2019-10-09**.

Was halttet ihr davon @flueders @jklmnn ?

**Comment by flueders** [comment]
Naja, was soll das bringen? Die Releases sind doch nur deshalb eingeführt worden, damit man z.B. schon für das nächste Semester Änderungen einbringen kann, aber noch das aktuelle Semester auf der Website angezeigt werden kann.

Dann könnten wir doch gleich auf den jeweils letzten Commit zurückgreifen, und brauchen die releases nicht

**Comment by lutz** [comment]
Ich finde die Versionierung nicht intuitiv genug daher der Vorschlag. Ich würde eigentlich am bestehenden System nichts ändern (schon gar nicht Codeanpassungen). Jeder kann Commits machen usw. nur dass wir bei den Tags statt wie bisher einfach das Datum nehmen und fertig.

**Comment by jklmnn** [comment]
Ich sehe keinen Grund, das Datum nicht zu nehmen. @flueders es gäbe schon noch Releases aber deren Name wäre einfach anders. Die einzige technische Bedingung, die ich sehe ist, dass die Tagnamen nach wie vor sortierbar sind, sodass der letzte am Ende steht damit er zuerst in der GitHub API auftaucht. Das Datum hätte den Vorteil, dass klar wäre, von welchem Stand die Daten sind (was aber auch im Commit steht). Außerdem muss man sich keinen Kopf machen welche Version die letzte war.
Übrigens sind mit dem aktuellen Schema maximal 9 bzw. 10 verschiedene Versionen pro Semester möglich. Das wäre ein Grund, etwas anderes zu verwenden.

**Comment by lutz** [comment]
@flueders  @jklmnn hat das gut zusammengefasst. Ich denke bevor wir eine andere fancy Versionierung finden ist dass ein recht einfacher Weg. Das Datum in dem vorgeschlagenen Format wäre ja sortierbar, sogar recht gut. Von daher würde ich es erstmal so machen mit dem nächsten Release!

**Comment by jklmnn** [comment]
Du musst nur aufpassen, dass die neue Version auch neuer aussieht als die bisherigen. Sonst sortiert GitHub die falsch ;)

**Comment by flueders** [comment]
Gut, von mir aus können wir das so machen ;)
